import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/main.scss";
import Providers from "@/shared/providers/Providers";
import SideBar from "@/shared/components/SideBar";
import TitlePage from "@/shared/components/TitlePage";
import WrapperPages from "@/shared/components/WrapperPages";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="pt-br">
      <body className="dashboard" id="main_content">
        <Providers>
            <SideBar />
            <TitlePage />
            <WrapperPages>
              {children}
            </WrapperPages>
        </Providers>
      </body>
    </html>
  );
}
